(push '("\\.chs$" . haskell-mode) auto-mode-alist)
(push '("\\.md$"   . markdown-mode) auto-mode-alist)
(push '("\\.text$" . markdown-mode) auto-mode-alist)
(push '("^wscript$" . python-mode) auto-mode-alist)

(require 'web-mode)
(add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))
;; web-mode is also used to edit plain html.
(add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
